version: 0.2

phases:
  install:
    commands:
      - sudo update-ca-certificates -f
  pre_build:
    commands:
      - echo Running maven clean
      - mvn -f mymarkcustomer/pom.xml clean
      - mvn -f mymarkcustomerapi/pom.xml clean
  build:
    commands:
      - echo Build started
      - mvn -f mymarkcustomerapi/pom.xml install -DskipTests
      - mvn -f mymarkcustomer/pom.xml install -DskipTests
      
  post_build:
    commands:
      - mv mymarkcustomer/target/mymarkcustomermicro.war mymarkcustomermicro.war

artifacts:
  files:
    - mymarkcustomermicro.war
