version: 0.2

phases:
  install:
    commands:
      - sudo update-ca-certificates -f
  pre_build:
    commands:
      - echo Running maven clean
      - mvn -f mymarkproduct/pom.xml clean
      - mvn -f mymarkproductapi/pom.xml clean
  build:
    commands:
      - echo Build started
      - mvn -f mymarkproductapi/pom.xml install -DskipTests
      - mvn -f mymarkproduct/pom.xml install -DskipTests
      
  post_build:
    commands:
      - mv mymarkproduct/target/mymarkproductmicro.jar mymarkproductmicro.jar

artifacts:
  files:
    - mymarkproductmicro.jar
