CREATE TABLE `PRODUCT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_CODE` varchar(30) NOT NULL,
  `PRICE` double NOT NULL,
  `NAME` varchar(80) NOT NULL,
  `SHORT_DESC` varchar(256) NOT NULL,
  `LONG_DESC` varchar(512) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROD_CODE_UNIQUE` (`PRODUCT_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE `INVENTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` int(11) NOT NULL,
  `SKU` varchar(30) NOT NULL,
  `STATUS` varchar(10) NOT NULL,
  `SELL_DATE` date DEFAULT NULL,
  `IN_PROCESS_DATE` date DEFAULT NULL,
  `RETURN_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SKU_UNIQUE` (`SKU`),
  KEY `PRODUCT_ID_FK` (`PRODUCT_ID`),
  CONSTRAINT `INVENTORY_PRODUCT_FK` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=93 DEFAULT CHARSET=utf8;
