-- Create USERS
CREATE TABLE `USERS` (
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `enabled` int(11) NOT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create AUTHORITIES
CREATE TABLE `AUTHORITIES` (
  `username` varchar(50) NOT NULL,
  `authority` varchar(50) NOT NULL,
  UNIQUE KEY `ix_auth_username` (`username`,`authority`),
  KEY `fk_authorities_users_idx` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create COUNTRY
CREATE TABLE `COUNTRY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(80) NOT NULL,
  `CODE` varchar(3) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE_UNIQUE` (`CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- Create STATE
CREATE TABLE `STATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(80) NOT NULL,
  `CODE` varchar(3) NOT NULL,
  `COUNTRY_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `COUNTRY_FK_idx` (`COUNTRY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8;

-- Create ADDRESS
CREATE TABLE `ADDRESS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(20) NOT NULL,
  `PRIMARY_LINE` varchar(80) NOT NULL,
  `SECONDARY_LINE` varchar(80) DEFAULT NULL,
  `CITY` varchar(80) NOT NULL,
  `ZIP_CODE` varchar(9) NOT NULL,
  `STATE_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `STATE_ID_idx` (`STATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create ACCOUNT
CREATE TABLE `ACCOUNT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(20) NOT NULL,
  `BILLING_ADDRESS_ID` int(11) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `BILLING_ADDRESS_FK_idx` (`BILLING_ADDRESS_ID`),
  KEY `ACCOUNT_CUST_FK_idx` (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=179 DEFAULT CHARSET=utf8;

-- Create CUSTOMER
CREATE TABLE `CUSTOMER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(20) NOT NULL,
  `FIRST_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `EMAIL` varchar(45) NOT NULL,
  `ACCOUNT_ID` int(11) DEFAULT NULL,
  `SHOPPING_CART_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME_UNIQUE` (`USER_NAME`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`),
  KEY `ACCOUNT_FK_idx` (`ACCOUNT_ID`),
  KEY `CUST_CART_FK_idx` (`SHOPPING_CART_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=174 DEFAULT CHARSET=utf8;

-- Create PRODUCT
CREATE TABLE `PRODUCT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_CODE` varchar(30) NOT NULL,
  `PRICE` double NOT NULL,
  `NAME` varchar(80) NOT NULL,
  `SHORT_DESC` varchar(256) NOT NULL,
  `LONG_DESC` varchar(512) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROD_CODE_UNIQUE` (`PRODUCT_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- Create INVENTORY
CREATE TABLE `INVENTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` int(11) NOT NULL,
  `STATUS` varchar(10) NOT NULL,
  `SELL_DATE` date DEFAULT NULL,
  `IN_PROCESS_DATE` date DEFAULT NULL,
  `RETURN_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PRODUCT_ID_FK` (`PRODUCT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8;

-- Create SHOPPING_CART
CREATE TABLE `SHOPPING_CART` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_FK_idx` (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=utf8;

-- Create CART_LINE_ITEM
CREATE TABLE `CART_LINE_ITEM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CART_ID` int(11) NOT NULL,
  `PRODUCT_ID` int(11) NOT NULL,
  `QUANTITY` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CART_PROD_UNQ_idx` (`CART_ID`,`PRODUCT_ID`),
  KEY `PRODUCT_FK_idx` (`PRODUCT_ID`),
  KEY `CART_FK_idx` (`CART_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=utf8;

CREATE TABLE `ORDERS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(20) NOT NULL,
  `CUSTOMER_ID` int(11) NOT NULL,
  `ORDER_DATE` date NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ORDER_CUST_FK_idx` (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8;

CREATE TABLE `ORDER_LINE_ITEM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` int(11) NOT NULL,
  `INVENTORY_ITEM_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `OLI_INVENTORY_FK_idx` (`INVENTORY_ITEM_ID`),
  KEY `OLI_ORDER_FK_idx` (`ORDER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=utf8;


ALTER TABLE `mymark_mono`.`ACCOUNT` 
ADD CONSTRAINT `ACCOUNT_CUST_FK` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`ACCOUNT` 
ADD CONSTRAINT `ACCOUNT_BILLING_ADDRESS_FK` FOREIGN KEY (`BILLING_ADDRESS_ID`) REFERENCES `ADDRESS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`ADDRESS` 
ADD CONSTRAINT `ADDRESS_STATE_FK` FOREIGN KEY (`STATE_ID`) REFERENCES `STATE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`AUTHORITIES` 
ADD CONSTRAINT `AUTH_USERS_FK` FOREIGN KEY (`username`) REFERENCES `USERS` (`username`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`CART_LINE_ITEM` 
ADD CONSTRAINT `CLI_CART_FK` FOREIGN KEY (`CART_ID`) REFERENCES `SHOPPING_CART` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`CART_LINE_ITEM` 
ADD CONSTRAINT `CLI_PRODUCT_FK` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`CUSTOMER` 
ADD CONSTRAINT `CUST_ACCOUNT_FK` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`CUSTOMER` 
ADD CONSTRAINT `CUST_CART_FK` FOREIGN KEY (`SHOPPING_CART_ID`) REFERENCES `SHOPPING_CART` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`INVENTORY` 
ADD CONSTRAINT `INVENTORY_PRODUCT_FK` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`ORDER_LINE_ITEM` 
ADD CONSTRAINT `OLI_INVENTORY_FK` FOREIGN KEY (`INVENTORY_ITEM_ID`) REFERENCES `INVENTORY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`ORDER_LINE_ITEM` 
ADD CONSTRAINT `OLI_ORDER_FK` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`ORDERS` 
ADD CONSTRAINT `ORDER_CUST_FK` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`SHOPPING_CART` 
ADD CONSTRAINT `CART_CUSTOMER_FK` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `mymark_mono`.`STATE` 
ADD CONSTRAINT `STATE_COUNTRY_FK` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
